# Generated by Django 5.0.9 on 2024-10-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(default='NGN', max_length=50),
        ),
    ]
