# Generated by Django 5.0.9 on 2024-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userwallet_balance_alter_userwallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(default='ZAR', max_length=50),
        ),
    ]
