# Generated by Django 4.2.3 on 2023-07-31 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the map was downloaded.', verbose_name='Download Date')),
                ('downloaded_map', models.CharField(help_text='The name or identifier of the downloaded map.', max_length=200, verbose_name='Downloaded Map')),
                ('user', models.ForeignKey(help_text='The user who downloaded the map.', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
