# Generated by Django 4.2.3 on 2023-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdownload',
            name='downloaded_map',
            field=models.CharField(blank=True, default='', help_text='The name or identifier of the downloaded map.', max_length=200, verbose_name='Downloaded Map'),
        ),
    ]
