# Generated by Django 4.2.3 on 2023-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_alter_formfield_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="contact_img_link",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
