# Generated by Django 5.0.9 on 2024-10-06 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('none', 'None')], max_length=4, verbose_name='title')),
                ('school', models.CharField(max_length=255, verbose_name='school')),
                ('position', models.CharField(max_length=255, verbose_name='position')),
                ('country', models.CharField(choices=[('angola', 'Angola'), ('botswana', 'Botswana'), ('comoros', 'Comoros'), ('democratic_republic_of_the_congo', 'Democratic Republic of the Congo'), ('eswatini', 'Eswatini'), ('lesotho', 'Lesotho'), ('madagascar', 'Madagascar'), ('malawi', 'Malawi'), ('mauritius', 'Mauritius'), ('mozambique', 'Mozambique'), ('namibia', 'Namibia'), ('seychelles', 'Seychelles'), ('south_africa', 'South Africa'), ('tanzania', 'Tanzania'), ('zambia', 'Zambia'), ('zimbabwe', 'Zimbabwe')], max_length=255, verbose_name='SADC Country')),
                ('secondary_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='secondary_email')),
                ('cell_org', models.CharField(max_length=255, verbose_name='cell')),
                ('cell', models.CharField(blank=True, max_length=255, null=True, verbose_name='cell')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='website')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('sace', models.CharField(blank=True, max_length=255, null=True, verbose_name='sace')),
                ('membership_type', models.CharField(choices=[('individual', 'Individual, SAGTA / AAG Joint Membership R480 / 1 year'), ('retired_teachers', 'Retired teachers, SAGTA / AAG Joint Membership R240 / 1 year'), ('student_teachers', 'Student teachers, SAGTA / AAG Joint Membership R240 / 1 year'), ('corporate_institutional', 'Corporate Institutional Membership (max. 5 staff members) R2200 / 1 year')], max_length=255, verbose_name='membership_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
