# Generated by Django 5.0.9 on 2024-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(choices=[('south_africa', 'South Africa'), ('angola', 'Angola'), ('botswana', 'Botswana'), ('comoros', 'Comoros'), ('democratic_republic_of_the_congo', 'Democratic Republic of the Congo'), ('eswatini', 'Eswatini'), ('lesotho', 'Lesotho'), ('madagascar', 'Madagascar'), ('malawi', 'Malawi'), ('mauritius', 'Mauritius'), ('mozambique', 'Mozambique'), ('namibia', 'Namibia'), ('seychelles', 'Seychelles'), ('tanzania', 'Tanzania'), ('zambia', 'Zambia'), ('zimbabwe', 'Zimbabwe')], max_length=255, verbose_name='SADC Country'),
        ),
    ]
