# Generated by Django 5.1.4 on 2025-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual, SAGTA / AAG Joint Membership R520 / 1 year'), ('retired_teachers', 'Retired teachers, SAGTA / AAG Joint Membership R260 / 1 year'), ('student_teachers', 'Student teachers, SAGTA / AAG Joint Membership R260 / 1 year'), ('corporate_institutional', 'Corporate Institutional Membership (max. 5 staff members) R2370 / 1 year')], max_length=255, verbose_name='membership_type'),
        ),
    ]
