# Generated by Django 5.1.4 on 2025-01-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cell_org',
            field=models.CharField(max_length=255, null=True, verbose_name='cell'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(choices=[('south_africa', 'South Africa'), ('angola', 'Angola'), ('botswana', 'Botswana'), ('comoros', 'Comoros'), ('democratic_republic_of_the_congo', 'Democratic Republic of the Congo'), ('eswatini', 'Eswatini'), ('lesotho', 'Lesotho'), ('madagascar', 'Madagascar'), ('malawi', 'Malawi'), ('mauritius', 'Mauritius'), ('mozambique', 'Mozambique'), ('namibia', 'Namibia'), ('seychelles', 'Seychelles'), ('tanzania', 'Tanzania'), ('zambia', 'Zambia'), ('zimbabwe', 'Zimbabwe')], max_length=255, null=True, verbose_name='SADC Country'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual, SAGTA / AAG Joint Membership R520 / 1 year'), ('retired_teachers', 'Retired teachers, SAGTA / AAG Joint Membership R260 / 1 year'), ('student_teachers', 'Student teachers, SAGTA / AAG Joint Membership R260 / 1 year'), ('corporate_institutional', 'Corporate Institutional Membership (max. 5 staff members) R2370 / 1 year')], max_length=255, null=True, verbose_name='membership_type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(max_length=255, null=True, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('none', 'None')], max_length=4, null=True, verbose_name='title'),
        ),
    ]
