# Generated by Django 5.2.8 on 2025-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_address_alter_member_cell_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual, SAGTA / AAG Joint Membership R600 / 1 year'), ('retired_teachers', 'Retired teachers, SAGTA / AAG Joint Membership R300 / 1 year'), ('student_teachers', 'Student teachers, SAGTA / AAG Joint Membership R300 / 1 year'), ('corporate_institutional', 'Corporate Institutional Membership (max. 5 staff members) R2560 / 1 year')], max_length=255, null=True, verbose_name='membership_type'),
        ),
    ]
