version: '3.7'
services:
  wsgi:
    image: sagtaweb:latest
    environment:
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      DEBUG: "${DEBUG}"
      SITE_NAME: "${SITE_NAME}"
      UWSGI_PORT: "8000"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      # Will also mount media, static, and sqlite db in that directory
      - ../:/code/

  nginx:
    image: nginx
    # let wsgi online first
    depends_on:
      - wsgi
    volumes:
      # mount config file directly
      - ./nginx.conf:/etc/nginx/conf.d/mysite.conf
      # mount only media and static to serve directly from nginx
      - ../media:/opt/sagtawebsite/media
      - ../static:/opt/sagtawebsite/static
    ports:
      - "${HTTP_PORT}:80"
