# Generated by Django 3.2.3 on 2021-07-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_img_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Prepshare Page',
                'verbose_name_plural': 'Prepshare Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
