# Generated by Django 5.2.4 on 2025-07-26 07:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', 2), ('full_richtext', 3), ('simple_richtext', 4), ('Raw_HTML', 5), ('cards', 13), ('carousel_image', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('streams.blocks.RichtextBlock', (), {}), 4: ('streams.blocks.SimpleRichtextBlock', (), {}), 5: ('streams.blocks.RawHTMLBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'If the button page above is selected, that will be used first.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('text', 8), ('button_page', 9), ('button_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('cards', 12)]], {}), 14: ('wagtail.blocks.StructBlock', [[('image', 6)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('images', 15)]], {})}, null=True),
        ),
    ]
