name: Every Two Hours HTTP Request with Basic Auth
on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours throughout the day
  workflow_dispatch:

jobs:
  send_request:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Prevent hanging requests
    steps:
      - name: Send HTTP Request
        run: |
          curl -f -X GET \
            --max-time 30 \
            --retry 3 \
            --retry-delay 10 \
            --retry-max-time 60 \
            -u "${{ secrets.BASIC_AUTH_USERNAME }}:${{ secrets.BASIC_AUTH_PASSWORD }}" \
            https://sagta.org.za/api/custom/check/
        env:
          # Optional: Set curl to be less verbose
          CURL_CA_BUNDLE: ""
